### ISSUE TITLE
Checking dependencies could have an opt-out option

### ISSUE THREAD

**Issue by edygar** [kentcdodds/use-deep-compare-effect#1]
- `use-deep-compare-effect` version: 1.1.0
- `node` version: 11
- `npm` (or `yarn`) version: 6

Relevant code or config

```javascript
useDeepCompare(doStuff, [ myCustomHookConsumerInputedValue ])
```

What you did:
I've tried to delegate the comparison of my consumer's input to useDeepCompare hook

What happened:

```
Error: useDeepCompareEffect should not be used with dependencies that are all primitive values. Use React.useEffect instead.
```
Reproduction repository:
Just pass primitive values to its comparison argument list 

Problem description:
While building my own custom hook, I maybe don't know yet the shape of all arguments that my hook's consumers may input to it, and as hooks aren't optional, I can't really check whether to use Effect or DeepCompareEffect hook.

Suggested solution:
`checkDeps` act as a linter, but one we can't ignore. Maybe we could have an option to not throw, so that in some cases we could own the risk. The opt-out option would discourage one to use it every time unwary.

**Comment by kentcdodds** [comment]
Sure. Let's make a new hook that doesn't do the check and call it: `useDeepCompareEffectNoCheck`

It'll be undocumented for now. What do you think? Would you like to http://makeapullrequest.com ?
