### ISSUE TITLE
Hook is not triggered when boolean property changed on nested object. 

### ISSUE THREAD

**Issue by dalisalvador** [kentcdodds/use-deep-compare-effect#13]
- `use-deep-compare-effect` version:1.3.0
- `node` version: 12.9.1
- `npm` (or `yarn`) version: 6.4.1

What you did: 
Passed an object (nested) as prop to a functional component

What happened:
One of the nested properties of the object is changed from false/true.

Problem description:
useDeepEffect is not triggered when object changed.

Suggested solution:
the only way I manage to achieve what I wanted is to by doing: JSON.stringify(nestedObject)

Object Structure:

```
nestedObject: {
 a: {another obj},
 array: [
         {b: Boolean},
         {c: Boolean},
         {d: Boolean},
       ]
}
```

Problem: Boolean 'C' changed, but useDeepEffect is not triggered.

**Comment by kentcdodds** [comment]
Could you make a codesandbox reproduction of this issue?

**Comment by dalisalvador** [comment]
@kentcdodds I'll try to write something similar... 
 I'm actually passing props (nested object) to the functional component through `mapStateToProps` and wrapping it with `connect` from `react-redux`. 

Something like:

```
const myFunc({...props}) => {

  const { nestedObject } = props;

  //Not working
  useDeepCompareEffect( ()=> {
         console.log("nested object changed")
  }, [nestedObject])

  //Working
  useEffect( ()=> {
         console.log("nested object changed")
  }, [JSON.stringify(nestedObject)])
....

}

const mapStateToProps = state => ({
  nestedObeject: state.nestedObject,
});

export default connect(mapStateToProps,  null)(myFunc);
```

The only thing that's changing is a nested Boolean.
Thanks a lot!

**Comment by trentonsnyder** [comment]
@dalisalvador https://codesandbox.io/s/wispy-night-gcsew
I tried to reproduce it by just changing a deeply nested bool. Redux shouldn't make a difference. I'm not seeing a problem.

**Comment by niamleeson** [comment]
@trentonsnyder That sandbox is setting a new object reference on button click so it seems like it is working correctly. Here's an actual reproduction of the bug: https://codesandbox.io/s/restless-star-c175j

**Comment by kotarella1110** [comment]
https://github.com/kentcdodds/use-deep-compare-effect/blob/master/src/__tests__/index.js#L82-L95

> this may be useful in the future, but we don't support it today so I thought it'd be good to include as a test as it would be a breaking change if we did add support. I'm inclined to not support this. Manipulation is not good.

**Comment by MadhuvanthG** [comment]
This could be fixed by creating a new reference to the `value` and then assigning it to `ref.current`. That way, when React does an `object.is`, it will see the change and trigger the effect.

@kentcdodds, What are your thoughts? I can open a quick PR.

**Comment by MadhuvanthG** [comment]
> https://github.com/kentcdodds/use-deep-compare-effect/blob/master/src/__tests__/index.js#L82-L95
> 
> > this may be useful in the future, but we don't support it today so I thought it'd be good to include as a test as it would be a breaking change if we did add support. I'm inclined to not support this. Manipulation is not good.

Ok, this sums it up, I think. Intentionally not supported and it makes sense.
