### ISSUE TITLE
doesn't work with sets

### ISSUE THREAD

**Issue by franleplant** [kentcdodds/use-deep-compare-effect#15]
- `use-deep-compare-effect` version: v1.3.0
- `node` version: 12
- `yarn` version: 1.21.1

Relevant code or config

```javascript
const set = new Set(props.someList)

useDeepCompareEffect(() => {
  // some effects
}, [set])
```

What you did:

I am trying to deeply compare a `Set` of values but it turns out that the underlying
`dequal` library doesnt handle `Set` comparison correctly.

example

```javascript
var dequal = require("dequal")

let a = new Set([1,2,3,4])
let b = new Set([1,2,3,4])

console.log(dequal(a,b))
```

Check it running here https://runkit.com/embed/yiu9lr2kont0

What happened:

Each set is computed as different even though they should be computed as equal.

Problem description:

`dequal` seems to be not best library to do deep equals

Suggested solution:

We could potentially choose one of three
- do a PR to `dequal` fixing this issue
- make the comparison mechanism a parameter in `useDeepCompareEffect`
- change to a more standard mechanism such as lodash's `isEqual` that does compute this Set equality appropriately 

hope this also helps documenting the current limitation of this otherwise awesome library.

Thanks a lot for everything and sorry to _bug_ you (Pawn Intended)

Fran

**Comment by kentcdodds** [comment]
Hi 👋

I much prefer to get this handled in dequal. Looks like that's likely to happen so I'll go ahead and close this here. Thanks!

**Comment by lukeed** [comment]
This is now supported in [`dequal@2.x`](https://github.com/lukeed/dequal/releases/tag/v2.0.0) using value equality.

**Comment by kentcdodds** [comment]
Sweet, I'll get that updated and we'll have set support! Woo!

**Comment by kentcdodds** [comment]
Thanks @lukeed!
