### ISSUE TITLE
useEffect should be used to set ref.current for concurrent mode

### ISSUE THREAD

**Issue by landvibe** [kentcdodds/use-deep-compare-effect#25]
I think useEffect should be used to set ref.current for concurrent mode
in [this line](https://github.com/kentcdodds/use-deep-compare-effect/blob/master/src/index.js#L25)

**Comment by kentcdodds** [comment]
Hi @landvibe,

Unfortunately that won't work. Go ahead and give it a try and you'll see why :)

**Comment by landvibe** [comment]
I know it won't work, I meant refactoring.
Because the current version is not stable with concurrent mode.

**Comment by kentcdodds** [comment]
I know it's not stable with concurrent mode, but what you're suggesting won't work at all. Feel free to prove be wrong 😉
