### ISSUE TITLE
use-deep-compare-effect breaks on IE11 due to dequal dependency not working on IE9+

### ISSUE THREAD

**Issue by andrei10k** [kentcdodds/use-deep-compare-effect#27]
Hey,

As you can see on the docs dequal is not working on IE9+. i found the issue on IE11, was breaking the app. Is it possible to use dequal/lite? 

https://www.npmjs.com/package/dequal

**Comment by kentcdodds** [comment]
@andrei10k, I'm afraid not because it doesn't support all data types we need to support.

Luckily the implementation is just a few lines of code so this is easily forkable :)
