### ISSUE TITLE
Code of conduct link is broken

### ISSUE THREAD

**Issue by maraisr** [kentcdodds/use-deep-compare-effect#31]
![image](https://user-images.githubusercontent.com/599459/100412403-53a35800-30c0-11eb-94e3-4cf68e23a3a2.png)

**Comment by maraisr** [comment]
Link in readme goes to `main` but the "main" branch is `master`

**Comment by kentcdodds** [comment]
Ah! Didn't notice your PR. I fixed it myself. Thanks anyway!
