### ISSUE TITLE
Warning during yarn install

### ISSUE THREAD

**Issue by daveisfera** [kentcdodds/use-deep-compare-effect#35]
- `use-deep-compare-effect` version: 1.5.0
- `node` version: 12.20.0
- `npm` version: 6.14.8
- `yarn` version: 1.22.10

What you did:
`yarn add use-deep-compare-effect`

What happened:
```
warning myproject > use-deep-compare-effect > @types/use-deep-compare-effect@1.5.1: This is a stub types definition. use-deep-compare-effect provides its own type definitions, so you do not need this installed.
```

Problem description:
Warning about types from `yarn install`

Suggested solution:
Remove dependency on @types/use-deep-compare-effect

**Comment by kentcdodds** [comment]
@daveisfera,

We don't have a dependency on `@types/use-deep-compare-effect`: https://github.com/kentcdodds/use-deep-compare-effect/blob/f5979ec228f87ceb8b459577c44c98bc76721cba/package.json#L27-L43

**Comment by daveisfera** [comment]
Sorry, looks like it was recently removed but hasn't been released yet:
https://github.com/kentcdodds/use-deep-compare-effect/commit/9f0893541af05c181f90f5458c718a5aec6e1488#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by kentcdodds** [comment]
Ah, thank you for opening this up! I'll get that released now.

**Comment by kentcdodds** [comment]
@all-contributors please add @daveisfera for bugs
