### ISSUE TITLE
Effect not called when doing `getDerivedStateFromProps`

### ISSUE THREAD

**Issue by AlbertLucianto** [kentcdodds/use-deep-compare-effect#40]
- `use-deep-compare-effect` version: 1.6.0

### What you did:
[Trying to achieve `getDerivedStateFromProps` with hooks](https://reactjs.org/docs/hooks-faq.html#how-do-i-implement-getderivedstatefromprops). In this case, the goal was to reset the `page` synchronously as the `keyword` changes (instead of using `useEffect` to avoid triggering a query twice).

### What happened:
![Screenshot 2020-12-17 at 10 56 02 PM](https://user-images.githubusercontent.com/23165866/102503830-162c5c00-40bb-11eb-8c54-ddb8c725c584.png)

Try typing on the search. It can be seen that the `useEffect` is called correctly the second time, while `useDeepCompareEffect` is not.

### Reproduction repository:
https://codesandbox.io/s/strange-night-icb1v?file=/src/App.js

### Problem description:
Doing `getDerivedStateFromProps` causes the component to **rerender twice**. However, from this PR #37 it's using a boolean flag, which switches between `true` and `false` in each render. The time `useEffect` checks the dependency, the flag was flipped twice, thus not called.

### Suggested solution:
Either remove the `signalRef` or using an increasing number instead.

Thanks a lot for this great library! My team and I've been using this library everywhere in our projects. 😊

**Comment by kentcdodds** [comment]
@AlbertLucianto I like your suggestion of an incrementing `number`. Thanks for opening the issue. Would you like to contribute the fix?

**Comment by kentcdodds** [comment]
@all-contributors please add @AlbertLucianto for bugs

**Comment by AlbertLucianto** [comment]
@kentcdodds Sure, let me work on it!
