### ISSUE TITLE
IE11 throwing error due to dequal

### ISSUE THREAD

**Issue by ramsunvtech** [kentcdodds/use-deep-compare-effect#50]
- `use-deep-compare-effect` version: 1.6.1
- `node` version: 12.x
- `npm` version: 6.x

Relevant code or config

```javascript
useDeepCompareEffect(() => {
   // impression tracking
}, [])
```

What you did:
Tested in IE11

What happened:
Throwing error `unexpected ;`

Reproduction repository:

Problem description:
Unable to deep compare in IE11 Browser and its throwing uncaught exception.

Suggested solution:
This happens mainly due to `dequal` library (deepEqual method) which is using `for...of` which is not polyfill-ed.
https://github.com/kentcdodds/use-deep-compare-effect/blob/main/src/index.ts#L32-L35

**Comment by kentcdodds** [comment]
Hi @ramsunvtech,

Sorry, this library doesn't support IE11. Feel free to fork. It's a pretty simple library.

**Comment by ramsunvtech** [comment]
Thanks Kent for the reply. we might skip the usage since its costly for every page impression in Page Component. i hope its recommended for that right?

**Comment by kentcdodds** [comment]
I don't understand your question

**Comment by ramsunvtech** [comment]
Can this custom hook consumed on every react page to capture impression for
analytics purposes? Which will be called before mounting for analytics
purpose :)

**Comment by kentcdodds** [comment]
Yeah, it could be used for that.
