### ISSUE TITLE
isPrimitive check is truthy when val is null

### ISSUE THREAD

**Issue by arichiardi** [kentcdodds/use-deep-compare-effect#51]
- `use-deep-compare-effect` version: 1.6.1
- `node` version: 12.22.4
- `npm` version: 7.20

Relevant code or config

```javascript
useDeepCompareEffect(() => {
    setInternalInterval(initialInterval)
  }, [initialInterval])

```

What you did:

The `initialInterval` value is `null` on first render by component/data flow design. Normally it would be an object.

What happened:

The library throws `useDeepCompareEffect should not be used with dependencies that are all primitive`

Problem description:

I was expecting the `null` not to be treated as primitive and therefore forbidden.

Suggested solution:

I am not sure this is the right approach but given `null` means absence of value (or something!) for both objects and arrays, I would probably handle it as part of the deep comparison.

A workaround there is to pass `{}` to the component or normalize it internally, so I am not really blocked, but I wanted to report this for thinking about it.

Probably there is a good reason why it is the way it is :smile: 

Thanks for this library!

**Comment by kentcdodds** [comment]
Hi @arichiardi,

Yeah, `null` is a primitive value. I'm not sure why you're using this package for an interval. You probably should use a regular useEffect for that.

**Comment by arichiardi** [comment]
@kentcdodds My interval is an object, wouldn't this library deep-compare it's keys?

Maybe I am misinterpreting :smile:

**Comment by kentcdodds** [comment]
I assumed that `initialInterval` was the return value from `setInterval`. In any case, go ahead and use what works :)

Cheers!
