### ISSUE TITLE
[Feature Request] TypeScript Definitions

### ISSUE THREAD

**Issue by tonghuashuo** [kentcdodds/use-deep-compare-effect#6]
Would you please add TypeScript definition to this module. Either in this repo. Or send PR to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) would be wonderful.

**Comment by kentcdodds** [comment]
I'm not sure this is a good package for people to be using. I'm still evaluating it.

If you want TS definitions, then feel free to submit something to DefinitelyTyped.

**Comment by donaldpipowitch** [comment]
If anyone needs something easy to copy'n'paste.

```ts
declare module 'use-deep-compare-effect' {
  import { useEffect } from 'react';
  const useDeepCompareEffect: typeof useEffect;
  export default useEffect;
}
```

**Comment by mciastek** [comment]
> If anyone needs something easy to copy'n'paste.
> 
> ```ts
> declare module 'use-deep-compare-effect' {
>   import { useEffect } from 'react';
>   const useDeepCompareEffect: typeof useEffect;
>   export default useEffect;
> }
> ```

Would you like to put it into DefinitelyTyped [repo](https://github.com/DefinitelyTyped/DefinitelyTyped)?

**Comment by BrunoQuaresma** [comment]
> I'm not sure this is a good package for people to be using. I'm still evaluating it.

@kentcdodds what do you think nowadays?

**Comment by kentcdodds** [comment]
I still have mixed feelings about it. So I don't talk about this package much and I advise people to avoid it if they can.

**Comment by JPeer264** [comment]
Types are now added in DefinitelyTyped

**Comment by kentcdodds** [comment]
Awesome, and now they'll be automatically downloaded for folks as well :) (similar to how @testing-library does it). https://github.com/kentcdodds/use-deep-compare-effect/commit/adf359758409b499332d2e4a4404dbf461b81254

Thanks folks!
