### ISSUE TITLE
eslint react hooks plugin not calling

### ISSUE THREAD

**Issue by creativemind1** [kentcdodds/use-deep-compare-effect#60]
How can we use react-hooks/exhaustive-deps eslint plugin while using use-deep-compare-effect? Right now it's not throwing any warnings/errors if the required dependencies are missing in the method.

**Comment by hbendev** [comment]
You have to modify your ESLint configuration, so that the rule is triggered on other hooks other than the built-in ones. See documentation [here](https://github.com/facebook/react/tree/main/packages/eslint-plugin-react-hooks#advanced-configuration).
